### ISSUE TITLE
Won't build on 10.8

### ISSUE THREAD

**Issue by stylerw** [tgray/lbdb#3]
Hello!  Thanks for maintaining this, but it's broken for OS X 10.8.  Please help!

**Comment by tgray** [comment]
I'm still stuck on 10.7.  So it will be a while before I can look at this.

**Comment by stylerw** [comment]
Ah, OK.  Maybe for Mavericks?

Will

**Comment by tgray** [comment]
It's on my todo list.  :)

For what it's worth, I got sick of the lbdb issues myself some time ago and wrote a mini-replacement in Python.  It hooks into a small Obj-C program for Address Book integration, but it also queries other tools, like mutt alias files and mu.  It's pretty easy to extend.  I don't think anyone other than me uses it though, so it might be rough around the edges.

https://github.com/tgray/muttqt

**Comment by stylerw** [comment]
Tim,

You're about to have a second user.  I'm not beholden to lbdb, and it sounds like your tool does just what I'd need to use mutt with OS X.  I'll brew it up today and let you know!

Will

**Comment by stylerw** [comment]
Tim,

Sorry to bug you, but I've got contacts working and querying, I can see previous LBDB contacts, both installed from Homebrew.  I've also edited the .muttqt.conf file to add in the osx_abook line.

However, when I try and query, I get:

stylerw: ~ $ muttqt -q 'jess'
Traceback (most recent call last):
  File "/usr/local/bin/muttqt", line 754, in <module>
    sys.exit(main())
  File "/usr/local/bin/muttqt", line 723, in main
    aliasDat.searchData(query)
  File "/usr/local/bin/muttqt", line 56, in searchData
    for l in self.data:
AttributeError: 'aliasData' object has no attribute 'data'

Any ideas?

Thanks!

Will

**Comment by tgray** [comment]
Hmm.   I clearly need better error catching and exception handling :)

Do you use mutt alias files in your setup?  I'm hoping you don't.  If not, remove the `mutt_alias` item from the `helpers` line in `.muttqt.conf`.

I'm hoping it was looking for a file that doesn't exist.  If you _do_ use mutt alias files, add the right location in the [alias] section on the `files` line, like so:

```
[alias]
files = ~/.mutt/aliases
```

**Comment by stylerw** [comment]
That did the trick.  Brilliant.  Mind if I advertise your little tool on my little mutt tutorial?

http://linguisticmystic.com/2012/03/17/in-defense-of-simplicity-why-i-keep-coming-back-to-mutt/

Thanks!

Will

**Comment by tgray** [comment]
Glad that worked out.

And that would be wonderful if you wanted to put it in your post. Here's possibly a less intimidating link for the casual user:

http://tgray.github.io/muttqt/

**Comment by stylerw** [comment]
Done.  Thanks so much for the software, it works great, and it's now recommended to the world!

Will
